import type { HandoffModel } from '../models/handoff-model';

export const handoffsMock: HandoffModel[] = [
  {
    handoffId: 'HOF-00021',
    title: 'Part A-1001 recurring issue handoff',
    sourceType: 'Agent',
    sourceRef: 'AI-Trace',
    destinationType: 'Agent',
    destinationRef: 'AI-CIS',
    ownerUserId: 'USR-004',
    ownerDisplay: 'Welding Supervisor',
    status: 'open',
    agingStage: 'pendingAcknowledgment',
    linkedObjectRef: 'A-1001',
    linkedObjectType: 'part',
    linkedThreadRef: 'THR-00018',
    ackRequired: true,
    ackState: 'pending',
    lastUpdatedAt: '2026-04-20 08:15 AM',
    visibilityHolders: ['Welding Lead', 'Welding Supervisor', 'Production Manager'],
    quickActions: [
      { type: 'acknowledge', label: 'Acknowledge' },
      { type: 'openHandoff', label: 'Open Handoff' },
      { type: 'openThread', label: 'Open Linked Thread' },
    ],
  },
  {
    handoffId: 'HOF-00022',
    title: 'Fixture readiness ownership transfer',
    sourceType: 'Supervisor',
    sourceRef: 'Welding Supervisor',
    destinationType: 'Department',
    destinationRef: 'Quality',
    ownerDisplay: 'Quality Lead',
    status: 'acknowledged',
    linkedObjectRef: 'LIR-P-014',
    linkedObjectType: 'report',
    linkedThreadRef: 'THR-00019',
    ackRequired: true,
    ackState: 'acknowledged',
    lastUpdatedAt: '2026-04-20 08:32 AM',
    visibilityHolders: ['Welding Supervisor', 'Quality Lead'],
    quickActions: [{ type: 'openHandoff', label: 'Open Handoff' }],
  },
  {
    handoffId: 'HOF-00023',
    title: 'Cross-shift follow-up handoff',
    sourceType: 'Lead',
    sourceRef: 'Welding Lead',
    destinationType: 'Lead',
    destinationRef: '2nd Shift Lead',
    ownerDisplay: '2nd Shift Lead',
    status: 'inProgress',
    linkedObjectRef: 'A-2204',
    linkedObjectType: 'part',
    ackRequired: false,
    ackState: 'notRequired',
    lastUpdatedAt: '2026-04-20 08:48 AM',
    quickActions: [{ type: 'openHandoff', label: 'Open Handoff' }],
  },
  {
    handoffId: 'HOF-00024',
    title: 'Completed routing confirmation',
    sourceType: 'Agent',
    sourceRef: 'AI-Connect',
    destinationType: 'Manager',
    destinationRef: 'Production Manager',
    ownerDisplay: 'Production Manager',
    status: 'completed',
    linkedObjectRef: 'BRC-00003',
    linkedObjectType: 'broadcast',
    ackRequired: false,
    ackState: 'notRequired',
    lastUpdatedAt: '2026-04-20 09:00 AM',
    quickActions: [{ type: 'viewHistory', label: 'View History' }],
  },
  {
    handoffId: 'HOF-00025',
    title: 'Escalated recurring issue handoff',
    sourceType: 'Supervisor',
    sourceRef: 'Laser Supervisor',
    destinationType: 'Manager',
    destinationRef: 'Production Manager',
    ownerDisplay: 'Production Manager',
    status: 'escalated',
    agingStage: 'escalationRisk',
    linkedObjectRef: 'ESC-00007',
    linkedObjectType: 'escalation',
    linkedThreadRef: 'THR-00021',
    ackRequired: true,
    ackState: 'pending',
    lastUpdatedAt: '2026-04-20 09:06 AM',
    visibilityHolders: ['Laser Supervisor', 'Production Manager', 'Upper Management'],
    quickActions: [
      { type: 'acknowledge', label: 'Acknowledge' },
      { type: 'escalate', label: 'Escalate' },
    ],
  },
  {
    handoffId: 'HOF-00026',
    title: 'Stalled ownership assignment',
    sourceType: 'Meeting',
    sourceRef: 'Delay Review',
    destinationType: 'Department',
    destinationRef: 'Welding',
    ownerDisplay: 'Welding Supervisor',
    status: 'open',
    agingStage: 'stalled',
    linkedObjectRef: 'MTG-00011',
    linkedObjectType: 'meeting',
    ackRequired: true,
    ackState: 'pending',
    lastUpdatedAt: '2026-04-20 09:12 AM',
    quickActions: [
      { type: 'confirmOwnership', label: 'Confirm Ownership' },
      { type: 'openHandoff', label: 'Open Handoff' },
    ],
  },
  {
    handoffId: 'HOF-00027',
    title: 'Supplier follow-up transfer',
    sourceType: 'Manager',
    sourceRef: 'Production Manager',
    destinationType: 'Department',
    destinationRef: 'Purchasing',
    ownerDisplay: 'Purchasing',
    status: 'open',
    agingStage: 'freshOpen',
    linkedObjectRef: 'PO-00117',
    linkedObjectType: 'report',
    ackRequired: false,
    ackState: 'notRequired',
    lastUpdatedAt: '2026-04-20 09:20 AM',
    quickActions: [{ type: 'openHandoff', label: 'Open Handoff' }],
  },
  {
    handoffId: 'HOF-00028',
    title: 'Quality verification handoff',
    sourceType: 'Department',
    sourceRef: 'Welding',
    destinationType: 'Department',
    destinationRef: 'Quality',
    ownerDisplay: 'Quality Lead',
    status: 'acknowledged',
    agingStage: 'freshOpen',
    linkedObjectRef: 'Q-4401',
    linkedObjectType: 'part',
    linkedThreadRef: 'THR-00024',
    ackRequired: true,
    ackState: 'acknowledged',
    lastUpdatedAt: '2026-04-20 09:31 AM',
    quickActions: [
      { type: 'openThread', label: 'Open Linked Thread' },
      { type: 'openHandoff', label: 'Open Handoff' },
    ],
  },
];
