import type { MeetingModel } from '../models/meeting-model';

export const meetingsMock: MeetingModel[] = [
  {
    meetingId: 'MTG-00011',
    title: 'Part A-1001 recurring delay review',
    meetingType: 'crossFunctional',
    scheduledAt: '2026-04-21 08:00 AM',
    ackState: 'pending',
    prepReadiness: 'warning',
    unreadPrepCount: 2,
    attendeeSummary: { required: 4, acknowledged: 2, pending: 2 },
    linkedReports: ['LIR-P-014'],
    linkedThreads: ['THR-00018'],
    agendaItems: ['Recurring delays', 'Cross-department coordination'],
    escalationState: 'warning',
    quickActions: [
      { type: 'acknowledge', label: 'Acknowledge' },
      { type: 'openMeeting', label: 'Open Meeting' },
      { type: 'openPrep', label: 'Open Prep' },
    ],
  },
  {
    meetingId: 'MTG-00012',
    title: 'Today welding standup',
    meetingType: 'department',
    scheduledAt: '2026-04-20 01:30 PM',
    ackState: 'acknowledged',
    prepReadiness: 'low',
    unreadPrepCount: 0,
    attendeeSummary: { required: 6, acknowledged: 6, pending: 0 },
    linkedReports: ['LIR-P-015'],
    linkedThreads: ['THR-00020'],
    agendaItems: ['Today priorities', 'Fixture repair follow-up'],
    quickActions: [
      { type: 'openMeeting', label: 'Open Meeting' },
      { type: 'openPrep', label: 'Open Prep' },
    ],
  },
  {
    meetingId: 'MTG-00013',
    title: 'Executive escalation review',
    meetingType: 'executive',
    scheduledAt: '2026-04-21 10:00 AM',
    ackState: 'pending',
    prepReadiness: 'critical',
    unreadPrepCount: 3,
    attendeeSummary: { required: 5, acknowledged: 3, pending: 2 },
    linkedReports: ['LIR-P-017'],
    linkedThreads: ['THR-00021'],
    agendaItems: ['Escalated visibility', 'Routing control risk'],
    escalationState: 'critical',
    quickActions: [
      { type: 'acknowledge', label: 'Acknowledge' },
      { type: 'openMeeting', label: 'Open Meeting' },
      { type: 'openThread', label: 'Open Linked Thread' },
    ],
  },
  {
    meetingId: 'MTG-00014',
    title: 'Unread prep package review',
    meetingType: 'review',
    scheduledAt: '2026-04-21 02:00 PM',
    ackState: 'acknowledged',
    prepReadiness: 'medium',
    unreadPrepCount: 4,
    attendeeSummary: { required: 3, acknowledged: 3, pending: 0 },
    linkedReports: ['LIR-P-016'],
    linkedThreads: ['THR-00023'],
    agendaItems: ['Prep packet review', 'Release readiness'],
    quickActions: [
      { type: 'openPrep', label: 'Open Prep' },
      { type: 'openMeeting', label: 'Open Meeting' },
    ],
  },
  {
    meetingId: 'MTG-00015',
    title: 'At-risk cross-functional readiness check',
    meetingType: 'crossFunctional',
    scheduledAt: '2026-04-22 09:00 AM',
    ackState: 'pending',
    prepReadiness: 'high',
    unreadPrepCount: 1,
    attendeeSummary: { required: 4, acknowledged: 1, pending: 3 },
    linkedReports: ['LIR-P-018'],
    linkedThreads: ['THR-00025'],
    agendaItems: ['Readiness gap', 'Ownership confirmation'],
    escalationState: 'high',
    quickActions: [
      { type: 'acknowledge', label: 'Acknowledge' },
      { type: 'openMeeting', label: 'Open Meeting' },
      { type: 'openPrep', label: 'Open Prep' },
    ],
  },
  {
    meetingId: 'MTG-00016',
    title: 'Resolved issue review closeout',
    meetingType: 'review',
    scheduledAt: '2026-04-22 11:00 AM',
    ackState: 'acknowledged',
    prepReadiness: 'low',
    unreadPrepCount: 0,
    attendeeSummary: { required: 2, acknowledged: 2, pending: 0 },
    linkedReports: ['LIR-P-012'],
    linkedThreads: ['THR-00024'],
    agendaItems: ['Closeout confirmation', 'Archive decision'],
    quickActions: [
      { type: 'openMeeting', label: 'Open Meeting' },
      { type: 'openReport', label: 'Open Linked Report' },
    ],
  },
  {
    meetingId: 'MTG-00017',
    title: 'Manager prep sync for production plan',
    meetingType: 'crossFunctional',
    scheduledAt: '2026-04-20 03:30 PM',
    ackState: 'pending',
    prepReadiness: 'warning',
    unreadPrepCount: 2,
    attendeeSummary: { required: 3, acknowledged: 2, pending: 1 },
    linkedReports: ['LIR-P-019'],
    linkedThreads: ['THR-00019'],
    agendaItems: ['Production plan', 'Meeting prep alignment'],
    quickActions: [
      { type: 'acknowledge', label: 'Acknowledge' },
      { type: 'openPrep', label: 'Open Prep' },
      { type: 'openMeeting', label: 'Open Meeting' },
    ],
  },
  {
    meetingId: 'MTG-00018',
    title: 'Department review for weld flow',
    meetingType: 'department',
    scheduledAt: '2026-04-23 07:00 AM',
    ackState: 'acknowledged',
    prepReadiness: 'medium',
    unreadPrepCount: 1,
    attendeeSummary: { required: 5, acknowledged: 5, pending: 0 },
    linkedReports: ['LIR-P-020'],
    linkedThreads: ['THR-00022'],
    agendaItems: ['Flow constraints', 'Next-step ownership'],
    quickActions: [
      { type: 'openMeeting', label: 'Open Meeting' },
      { type: 'openPrep', label: 'Open Prep' },
    ],
  },
];
