import type { MyWorkItemModel } from '../models/my-work-item-model';

export const myWorkMock: MyWorkItemModel[] = [
  {
    itemId: 'MW-001',
    itemType: 'alert',
    title: 'Fixture readiness issue needs review',
    linkedObjectRef: 'LIR-P-014',
    linkedObjectType: 'report',
    status: 'Open',
    severity: 'high',
    ackRequired: true,
    ackState: 'pending',
    timestamp: '2026-04-20 08:15 AM',
    quickActions: [
      { type: 'acknowledge', label: 'Acknowledge' },
      { type: 'openLinkedObject', label: 'Open Report' },
    ],
  },
  {
    itemId: 'MW-002',
    itemType: 'handoff',
    title: 'Part A-1001 recurring issue handoff',
    linkedObjectRef: 'HOF-00021',
    linkedObjectType: 'handoff',
    status: 'Open',
    severity: 'medium',
    ackRequired: true,
    ackState: 'pending',
    timestamp: '2026-04-20 08:25 AM',
    quickActions: [
      { type: 'acknowledge', label: 'Acknowledge' },
      { type: 'openHandoff', label: 'Open Handoff' },
    ],
  },
  {
    itemId: 'MW-003',
    itemType: 'thread',
    title: 'Cross-department coordination thread has unread replies',
    linkedObjectRef: 'THR-00018',
    linkedObjectType: 'thread',
    status: 'Unread',
    severity: 'medium',
    ackRequired: false,
    ackState: 'notRequired',
    timestamp: '2026-04-20 08:40 AM',
    quickActions: [
      { type: 'openThread', label: 'Open Thread' },
      { type: 'reply', label: 'Reply' },
    ],
  },
  {
    itemId: 'MW-004',
    itemType: 'meeting',
    title: 'Delay review meeting needs acknowledgment',
    linkedObjectRef: 'MTG-00011',
    linkedObjectType: 'meeting',
    status: 'Needs Acknowledgment',
    severity: 'warning',
    ackRequired: true,
    ackState: 'pending',
    timestamp: '2026-04-20 08:50 AM',
    quickActions: [
      { type: 'acknowledge', label: 'Acknowledge' },
      { type: 'openMeeting', label: 'Open Meeting' },
    ],
  },
  {
    itemId: 'MW-005',
    itemType: 'handoff',
    title: 'Ownership confirmation pending on stalled handoff',
    linkedObjectRef: 'HOF-00022',
    linkedObjectType: 'handoff',
    status: 'Stalled',
    severity: 'high',
    ackRequired: true,
    ackState: 'pending',
    timestamp: '2026-04-20 09:05 AM',
    quickActions: [
      { type: 'confirmOwnership', label: 'Confirm Ownership' },
      { type: 'openHandoff', label: 'Open Handoff' },
    ],
  },
  {
    itemId: 'MW-006',
    itemType: 'escalation',
    title: 'Escalated coordination issue needs visibility',
    linkedObjectRef: 'ESC-00007',
    linkedObjectType: 'escalation',
    status: 'Escalated',
    severity: 'critical',
    ackRequired: false,
    ackState: 'notRequired',
    timestamp: '2026-04-20 09:10 AM',
    quickActions: [
      { type: 'open', label: 'Open Escalation Context' },
      { type: 'escalate', label: 'Retain Visibility' },
    ],
  },
  {
    itemId: 'MW-007',
    itemType: 'meeting',
    title: 'Unread prep items exist for cross-functional review',
    linkedObjectRef: 'MTG-00012',
    linkedObjectType: 'meeting',
    status: 'Unread Prep',
    severity: 'medium',
    ackRequired: false,
    ackState: 'notRequired',
    timestamp: '2026-04-20 09:20 AM',
    quickActions: [
      { type: 'openPrep', label: 'Open Prep' },
      { type: 'openMeeting', label: 'Open Meeting' },
    ],
  },
  {
    itemId: 'MW-008',
    itemType: 'alert',
    title: 'Reminder: linked report requires follow-up',
    linkedObjectRef: 'LIR-P-015',
    linkedObjectType: 'report',
    status: 'Open',
    severity: 'low',
    ackRequired: false,
    ackState: 'notRequired',
    timestamp: '2026-04-20 09:30 AM',
    quickActions: [
      { type: 'openReport', label: 'Open Report' },
      { type: 'openLinkedObject', label: 'Open Linked Object' },
    ],
  },
];
