import type { NotificationModel } from '../models/notification-model';

export const notificationsMock: NotificationModel[] = [
  {
    notificationId: 'NTF-001',
    type: 'notice',
    title: 'Shift summary has been posted',
    linkedObjectRef: 'SUM-00011',
    linkedObjectType: 'report',
    priority: 'low',
    readState: 'read',
    ackRequired: false,
    ackState: 'notRequired',
    timestamp: '2026-04-20 07:45 AM',
    deliveryContext: 'Welding / Supervisor scope',
    quickActions: [{ type: 'openLinkedObject', label: 'Open Report' }],
  },
  {
    notificationId: 'NTF-002',
    type: 'alert',
    title: 'Fixture readiness issue needs immediate review',
    linkedObjectRef: 'LIR-P-014',
    linkedObjectType: 'report',
    priority: 'high',
    readState: 'unread',
    ackRequired: true,
    ackState: 'pending',
    timestamp: '2026-04-20 08:15 AM',
    deliveryContext: 'Welding / Supervisor scope',
    quickActions: [
      { type: 'acknowledge', label: 'Acknowledge' },
      { type: 'openLinkedObject', label: 'Open Report' },
    ],
  },
  {
    notificationId: 'NTF-003',
    type: 'reminder',
    title: 'Follow-up required on repeat part review',
    linkedObjectRef: 'A-1001',
    linkedObjectType: 'part',
    priority: 'medium',
    readState: 'unread',
    ackRequired: false,
    ackState: 'notRequired',
    timestamp: '2026-04-20 08:28 AM',
    deliveryContext: 'Welding / Lead + Supervisor',
    quickActions: [{ type: 'openLinkedObject', label: 'Open Linked Object' }],
  },
  {
    notificationId: 'NTF-004',
    type: 'escalation',
    title: 'Recurring issue has been escalated for visibility',
    linkedObjectRef: 'ESC-00007',
    linkedObjectType: 'escalation',
    priority: 'critical',
    readState: 'unread',
    ackRequired: true,
    ackState: 'pending',
    timestamp: '2026-04-20 08:41 AM',
    deliveryContext: 'Cross-department escalation scope',
    quickActions: [
      { type: 'acknowledge', label: 'Acknowledge' },
      { type: 'open', label: 'Open Escalation Context' },
    ],
  },
  {
    notificationId: 'NTF-005',
    type: 'meeting',
    title: 'Delay review meeting needs acknowledgment',
    linkedObjectRef: 'MTG-00011',
    linkedObjectType: 'meeting',
    priority: 'warning',
    readState: 'unread',
    ackRequired: true,
    ackState: 'pending',
    timestamp: '2026-04-20 08:50 AM',
    deliveryContext: 'Meeting / Required attendee',
    quickActions: [
      { type: 'acknowledge', label: 'Acknowledge' },
      { type: 'openMeeting', label: 'Open Meeting' },
    ],
  },
  {
    notificationId: 'NTF-006',
    type: 'handoff',
    title: 'Ownership transferred for Part A-1001 issue',
    linkedObjectRef: 'HOF-00021',
    linkedObjectType: 'handoff',
    priority: 'medium',
    readState: 'read',
    ackRequired: true,
    ackState: 'acknowledged',
    timestamp: '2026-04-20 09:02 AM',
    deliveryContext: 'Welding Supervisor ownership lane',
    quickActions: [{ type: 'openHandoff', label: 'Open Handoff' }],
  },
  {
    notificationId: 'NTF-007',
    type: 'broadcast',
    title: 'Operations broadcast issued for today’s coordination plan',
    linkedObjectRef: 'BRC-00003',
    linkedObjectType: 'broadcast',
    priority: 'medium',
    readState: 'unread',
    ackRequired: false,
    ackState: 'notRequired',
    timestamp: '2026-04-20 09:12 AM',
    deliveryContext: 'Operations-wide broadcast',
    quickActions: [{ type: 'openBroadcast', label: 'Open Broadcast' }],
  },
  {
    notificationId: 'NTF-008',
    type: 'alert',
    title: 'Linked report still requires follow-up action',
    linkedObjectRef: 'LIR-P-015',
    linkedObjectType: 'report',
    priority: 'high',
    readState: 'read',
    ackRequired: false,
    ackState: 'notRequired',
    timestamp: '2026-04-20 09:30 AM',
    deliveryContext: 'Welding / Supervisor scope',
    quickActions: [
      { type: 'openReport', label: 'Open Report' },
      { type: 'openLinkedObject', label: 'Open Linked Object' },
    ],
  },
];
